# Generated by Django 5.1.1 on 2024-09-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoimages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
